apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name}}-dpm
  namespace: {{ .Values.namespace }}
  labels:
    app: web
    env: dev
    managed-by: Helm
    version: v1
spec:
  selector:
    matchLabels:
      app: web
      env: dev
  {{- if .Values.deployment.replica_count }}
  replicas: {{ .Values.deployment.replica_count }}
  {{- end }}
  template:
    metadata:
      labels:
        app: web
        env: dev
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.deployment.image }}
        ports:
          - containerPort : {{ .Values.deployment.containerPort }}
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5