environment: prod

namespace: default

database:
  host: mysql
  db_name: bookstore
  user: root
  password: "ZWVGb1d6dllqbg=="

deployment:
  replica_count: 1
  containerPort: 3000

service:
  port: 3000