apiVersion: apps/v1
kind: Deployment

metadata:
  name: shopui-{{ .Values.environment }}

spec:
  selector:
    matchLabels:
      app: shopui-{{ .Values.environment }}

  {{- if .Values.deployment.replica_count }}
  replicas: {{ .Values.deployment.replica_count }}
  {{- end }}
  
  template:

    metadata:
      labels:
        app: shopui-{{ .Values.environment }}
    spec:
      containers:
      - name: shopui-{{ .Values.environment }}
        image: devteds/demo-bookstore-shopui:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
