name: Apply backend Helm Chart to AKS

on:
  push:
    paths:
      - kubernetes/webapp-helm-charts/envs/prod/shopapi-chart/values.yaml
      - kubernetes/webapp-helm-charts/envs/prod/shopui-chart/values.yaml
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    name: Apply backend Helm Charts to AKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to github repo
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        helm version

    - name: Check if shopapi Helm release exists
      id: check-helm-release
      run: |
        if helm list -n default | grep -q 'shopapi'; then
          echo "::set-output name=shopapi_release_exists::true"
        else
          echo "::set-output name=shopapi_release_exists::false"
        fi

    - name: Apply shopapi with Helm
      if: steps.check-helm-release.outputs.shopapi_release_exists == 'false'
      run: |
        cd ./kubernetes/webapp-helm-charts/helm-charts
        helm install shopapi ./shopapi-chart --values ../envs/prod/shopapi-chart/values.yaml --wait

    - name: Upgrade shopapi with Helm
      if: steps.check-helm-release.outputs.shopapi_release_exists == 'true'
      run: |
        cd ./kubernetes/webapp-helm-charts/helm-charts
        helm upgrade shopapi ./shopapi-chart --values ../envs/prod/shopapi-chart/values.yaml --wait

    - name: Check if shopui Helm release exists
      id: check-helm-release
      run: |
        if helm list -n default | grep -q 'shopui'; then
          echo "::set-output name=shopui_release_exists::true"
        else
          echo "::set-output name=shopui_release_exists::false"
        fi

    - name: Apply shopui with Helm
      if: steps.check-helm-release.outputs.shopui_release_exists == 'false'
      run: |
        cd ./kubernetes/webapp-helm-charts/helm-charts
        helm install shopui ./shopui-chart --values ../envs/prod/shopui-chart/values.yaml --wait

    - name: Upgrade shopui with Helm
      if: steps.check-helm-release.outputs.shopui_release_exists == 'true'
      run: |
        cd ./kubernetes/webapp-helm-charts/helm-charts
        helm upgrade shopui ./shopui-chart --values ../envs/prod/shopui-chart/values.yaml --wait
